defaults: &defaults
  adapter: mysql
  username: root
  password:
  host: localhost

development:
  adapter: mysql
  database: triviapad
  <<: *defaults

test:
  database: triviapad_test
  <<: *defaults
